return {
  RemixIcons = loadstring(httpget("https://raw.githubusercontent.com/AlexanderTheWorst/Kairo/refs/heads/main/IconPacks/RemixIcons/assets.luau"))(),
  MaterialIcons_400_24_rounded = loadstring(httpget("https://raw.githubusercontent.com/AlexanderTheWorst/Kairo/refs/heads/main/IconPacks/MaterialIcons_400_24_rounded/assets.luau"))(),
  Lucide = loadstring(httpget("https://raw.githubusercontent.com/AlexanderTheWorst/Kairo/refs/heads/main/IconPacks/Lucide/assets.luau"))(),
  Tabler = loadstring(httpget("https://raw.githubusercontent.com/AlexanderTheWorst/Kairo/refs/heads/main/IconPacks/Tabler/assets.luau"))(),
}
